export const animeData = [
  {
    title: "Inu x Boku SS",
    image_url: "https://cdn.myanimelist.net/images/anime/12/35893.jpg",
    episodes: 12,
    rating: "PG-13 - Teens 13 or older",
    score: 7.63,
    genre: "Comedy, Supernatural, Romance, Shounen",
  },
  {
    title: "Seto no Hanayome",
    image_url: "https://cdn.myanimelist.net/images/anime/13/58383.jpg",
    episodes: 26,
    rating: "PG-13 - Teens 13 or older",
    score: 7.89,
    genre: "Comedy, Parody, Romance, School, Shounen",
  },
  {
    title: "Shugo Chara!! Doki",
    image_url: "https://cdn.myanimelist.net/images/anime/11/10645.jpg",
    episodes: 51,
    rating: "PG - Children",
    score: 7.55,
    genre: "Comedy, Magic, School, Shoujo",
  },
  {
    title: "Princess Tutu",
    image_url: "https://cdn.myanimelist.net/images/anime/13/32209.jpg",
    episodes: 38,
    rating: "PG-13 - Teens 13 or older",
    score: 8.21,
    genre: "Comedy, Drama, Magic, Romance, Fantasy",
  },
  {
    title: "Bakuman. 3rd Season",
    image_url: "https://cdn.myanimelist.net/images/anime/6/41845.jpg",
    episodes: 25,
    rating: "PG-13 - Teens 13 or older",
    score: 8.67,
    genre: "Comedy, Drama, Romance, Shounen",
  },
  {
    title: "Yume-iro PÃ¢tissiÃ¨re",
    image_url: "https://cdn.myanimelist.net/images/anime/12/21674.jpg",
    episodes: 50,
    rating: "G - All Ages",
    score: 8.03,
    genre: "Kids, School, Shoujo",
  },
  {
    title: "Ultra Maniac",
    image_url: "https://cdn.myanimelist.net/images/anime/8/53571.jpg",
    episodes: 26,
    rating: "G - All Ages",
    score: 7.26,
    genre: "Magic, Comedy, Romance, School, Shoujo",
  },
  {
    title: "Shakugan no Shana II (Second)",
    image_url: "https://cdn.myanimelist.net/images/anime/10/18669.jpg",
    episodes: 24,
    rating: "PG-13 - Teens 13 or older",
    score: 7.72,
    genre: "Action, Drama, Fantasy, Romance, School, Supernatural",
  },
  {
    title: "Nodame Cantabile: Paris-hen",
    image_url: "https://cdn.myanimelist.net/images/anime/4/11918.jpg",
    episodes: 11,
    rating: "PG-13 - Teens 13 or older",
    score: 8.24,
    genre: "Music, Slice of Life, Comedy, Romance, Josei",
  },
  {
    title: "Ouran Koukou Host Club",
    image_url: "https://cdn.myanimelist.net/images/anime/2/71992.jpg",
    episodes: 26,
    rating: "PG-13 - Teens 13 or older",
    score: 8.34,
    genre: "Comedy, Harem, Romance, School, Shoujo",
  },
  {
    title: "Junjou Romantica 2",
    image_url: "https://cdn.myanimelist.net/images/anime/6/38417.jpg",
    episodes: 12,
    rating: "PG-13 - Teens 13 or older",
    score: 8.15,
    genre: "Comedy, Drama, Romance, Shounen Ai",
  },
  {
    title: "Kaichou wa Maid-sama!",
    image_url: "https://cdn.myanimelist.net/images/anime/6/25254.jpg",
    episodes: 26,
    rating: "PG-13 - Teens 13 or older",
    score: 8.2,
    genre: "Comedy, Romance, School, Shoujo",
  },
  {
    title: "Sekaiichi Hatsukoi 2",
    image_url: "https://cdn.myanimelist.net/images/anime/8/34871.jpg",
    episodes: 12,
    rating: "PG-13 - Teens 13 or older",
    score: 8.23,
    genre: "Comedy, Drama, Romance, Shounen Ai",
  },
  {
    title: "Tonari no Kaibutsu-kun",
    image_url: "https://cdn.myanimelist.net/images/anime/4/39779.jpg",
    episodes: 13,
    rating: "PG-13 - Teens 13 or older",
    score: 7.71,
    genre: "Slice of Life, Comedy, Romance, School, Shoujo",
  },
  {
    title: "Bleach",
    image_url: "https://cdn.myanimelist.net/images/anime/3/40451.jpg",
    episodes: 366,
    rating: "PG-13 - Teens 13 or older",
    score: 7.9,
    genre: "Action, Adventure, Comedy, Super Power, Supernatural, Shounen",
  },
  {
    title: "Chobits",
    image_url: "https://cdn.myanimelist.net/images/anime/4/24648.jpg",
    episodes: 26,
    rating: "PG-13 - Teens 13 or older",
    score: 7.53,
    genre: "Sci-Fi, Comedy, Drama, Romance, Ecchi, Seinen",
  },
  {
    title: "Kimi ni Todoke",
    image_url: "https://cdn.myanimelist.net/images/anime/7/17890.jpg",
    episodes: 25,
    rating: "PG-13 - Teens 13 or older",
    score: 8.13,
    genre: "Slice of Life, Drama, Romance, School, Shoujo",
  },
  {
    title: "Naruto: Shippuuden",
    image_url: "https://cdn.myanimelist.net/images/anime/5/17407.jpg",
    episodes: 500,
    rating: "PG-13 - Teens 13 or older",
    score: 8.18,
    genre: "Action, Adventure, Comedy, Super Power, Martial Arts, Shounen",
  },
  {
    title: "Ranma Â½",
    image_url: "https://cdn.myanimelist.net/images/anime/13/6441.jpg",
    episodes: 161,
    rating: "R+ - Mild Nudity",
    score: 7.85,
    genre: "Slice of Life, Comedy, Martial Arts, Fantasy",
  },
];

// export default animeData;
